# fly.toml app configuration file generated for echo-notes-api on 2026-02-17T16:17:27-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'echo-notes-api'
